// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://saoyjrquvkhzcyrqqlmd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNhb3lqcnF1dmtoemN5cnFxbG1kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4NTE0ODYsImV4cCI6MjA3MDQyNzQ4Nn0.gHQZ1Lg4RbnRnzbVv9CK2gKGAQR82-OTllWSK5Fmj2Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});